#!/usr/bin/env bash
#
# Provision an Ubuntu 24.04 host to serve Everything4Cats.
#
# This is the server-side mirror of docker/Dockerfile and docker/entrypoint.sh.
# The container was built by hand, one step at a time, so that this script could
# be written from something already proven rather than from a guess. Where the
# two differ, the difference is deliberate and commented.
#
# Provider-neutral by construction. Everything between here and the "Done"
# banner targets Ubuntu, not a provider, and has been verified to run unchanged
# on a bare ubuntu:24.04 image twice in a row. The provider-specific parts are
# confined to one block, at the bottom, under "Remaining". Keeping them there is
# what made retargeting to AWS Lightsail on 2026-08-10 an edit to prose rather
# than to code, and it is worth preserving for the same reason.
#
#   # ON SERVER
#   sudo SITE_DOMAIN=everything4cats.ca SITE_TITLE='Everything4Cats' \
#        ADMIN_USER=casey ADMIN_EMAIL=you@example.com \
#        bash scripts/provision.sh
#
# `sudo` rather than a root shell because Ubuntu cloud images differ in whether
# root can log in at all. A Lightsail Ubuntu instance logs in as `ubuntu` with
# root SSH disabled. Under sudo that works, and so does a host that does permit
# root, so one invocation is correct everywhere.
#
# Passwords are never arguments, never defaults, and never written to this file.
# The script prompts for them with a silent read, so they stay out of the shell
# history, out of the process list, and out of the repository. That is tier 0 in
# AGENTS.md and the reason wp-config.php is not generated by the container
# entrypoint either.
#
# Idempotent: safe to re-run. Every step checks for its own result first, so a
# re-run after a failure resumes rather than duplicating.

set -euo pipefail

SKIPS=0

# --- configuration ----------------------------------------------------------

SITE_DOMAIN="${SITE_DOMAIN:-}"
SITE_TITLE="${SITE_TITLE:-Everything4Cats}"

# The scheme WP_HOME and WP_SITEURL are pinned to. https everywhere a browser
# will actually reach this over the network, which is the default and should
# stay the default. The one legitimate reason to set it to http is a site that
# is only ever reached through an SSH tunnel on localhost, where there is no
# certificate and no need for one.
SITE_SCHEME="${SITE_SCHEME:-https}"
ADMIN_USER="${ADMIN_USER:-}"
ADMIN_EMAIL="${ADMIN_EMAIL:-}"
# Optional. The public byline, kept distinct from ADMIN_USER so the login is not
# published in the Article schema. See the core-install block for why.
ADMIN_DISPLAY_NAME="${ADMIN_DISPLAY_NAME:-}"

WP_DIR="/var/www/everything4cats"
DB_NAME="${DB_NAME:-everything4cats}"
DB_USER="${DB_USER:-everything4cats}"

# SKIP_PACKAGES=1 skips the apt block. Set it when running this inside the
# project's own container, where the image already carries the whole stack.
# Re-running apt there is not merely redundant: mysql-server's postinst wants
# to start the server, which works during a docker build and fails through
# docker exec, so an unlucky apt upgrade turns a working container into a
# broken one. Everything after the apt block is identical either way.
SKIP_PACKAGES="${SKIP_PACKAGES:-}"

# BEHIND_TLS_PROXY=1 when something else terminates HTTPS and forwards plain
# HTTP here, which is what a CDN or a reverse proxy in front of this host does.
# Unset for a Lightsail instance running certbot on the box, which is the
# current setup. Without it WordPress sees http, compares that to an https
# WP_HOME, and
# issues a canonical redirect to https, which the proxy forwards back as http:
# an infinite redirect loop that looks like a DNS or certificate fault and is
# neither.
BEHIND_TLS_PROXY="${BEHIND_TLS_PROXY:-}"

# The repository, so the theme can be deployed from it. Defaults to the checkout
# this script is being run from.
REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

# Leave whatever directory the operator happened to be standing in.
#
# Everything below addresses files by absolute path, so the working directory is
# never read. It is still inherited, and that is the problem: this script runs
# most WordPress work as `sudo -u www-data wp`, and a child process inherits the
# cwd of its parent. Ubuntu creates /home/ubuntu as 0750, so www-data cannot
# traverse it.
#
# Most wp commands survive that, because they only read files by absolute path.
# `wp rewrite structure` does not: it spawns a subprocess through proc_open, and
# posix_spawn fails with EACCES when the child cannot resolve its own working
# directory. The failure is reported as a PHP TypeError deep inside the WP-CLI
# phar, naming proc_close and a boolean, which says nothing about directory
# permissions and sends the reader looking at WP-CLI instead.
#
# Observed 2026-08-12 on the live host, running this script from ~ as the ubuntu
# user. The container harness never caught it because Docker's default working
# directory is /, which every user can traverse.
#
# / is chosen rather than $REPO_DIR because a checkout can itself sit somewhere
# unreadable, which would reintroduce exactly this bug.
cd /

log()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

# Is this a real host with an init system, or a container?
#
# The script has to run in both. A plain container has no systemd, no ufw that
# can load kernel modules, and no swap it is allowed to create, and PLAN.md
# already records that as the container's known limitation. Guarding these three
# is what lets the whole WordPress-shaped part of this script be tested in a
# throwaway container before it is ever pointed at a paid instance that costs
# money and takes a rebuild to fix.
#
# The guards skip; they never fake. A skipped step says so, loudly, so a
# container run is never mistaken for a full one.
has_systemd() { [ -d /run/systemd/system ]; }

# Start or restart a service through whichever mechanism exists.
svc() {
	if has_systemd; then
		systemctl "$1" "$2"
	else
		service "$2" "$1" >/dev/null 2>&1 || true
	fi
}
warn() { printf '\033[33mwarning: %s\033[0m\n' "$*" >&2; }
skipped() { printf '\033[33m   SKIPPED — %s\033[0m\n' "$*"; SKIPS=$((SKIPS+1)); }
die()  { printf '\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root: sudo bash scripts/provision.sh"
[ -n "$SITE_DOMAIN" ] || die "SITE_DOMAIN is required, for example SITE_DOMAIN=example.com"
[ -n "$ADMIN_USER" ]  || die "ADMIN_USER is required."
[ -n "$ADMIN_EMAIL" ] || die "ADMIN_EMAIL is required."

# --- guard: do not clobber a site this script does not own -------------------
#
# A provisioning script that silently disables another vhost, or overwrites
# another site's document root, is the single most damaging thing in this file.
# So it refuses rather than assumes.
#
# This stays even though the target is a dedicated instance. The script is
# idempotent and built to be re-run, and a re-run months from now meets whatever
# the host has become in the meantime, not the empty machine it first saw.

if [ -e "$WP_DIR" ] && [ ! -e "$WP_DIR/wp-includes/version.php" ]; then
	die "$WP_DIR exists but is not a WordPress install. Refusing to touch it."
fi

for conf in /etc/apache2/sites-enabled/*.conf; do
	[ -e "$conf" ] || continue
	case "$(basename "$conf")" in
		everything4cats.conf|000-default.conf) continue ;;
	esac
	warn "another enabled vhost is present: $(basename "$conf")"
	warn "this script only adds everything4cats.conf and never disables anything else."
done

# --- packages ---------------------------------------------------------------
#
# The same list the Dockerfile installs. The PHP extensions are separate Debian
# packages, and a missing one surfaces as a blank 500 with nothing in the error
# log, because WordPress calls wp_die() rather than raising a PHP error. That
# cost a debugging session in the container; it is spelled out here so it cannot
# cost another one on the server.

log "Installing packages"
if [ -n "$SKIP_PACKAGES" ]; then
	skipped "packages: SKIP_PACKAGES is set, the image already carries the stack"
else
	export DEBIAN_FRONTEND=noninteractive
	apt-get update -qq
	apt-get install -y -qq --no-install-recommends \
		ca-certificates curl less nano \
		apache2 \
		php-fpm php-mysql php-curl php-xml php-mbstring php-zip php-gd php-intl \
		mysql-server \
		certbot python3-certbot-apache \
		fail2ban \
		ufw
fi

# --- apache -----------------------------------------------------------------

log "Configuring Apache"

# The FPM conf name carries the PHP version, which differs between Ubuntu
# releases. Discovering it is what keeps this script working across an upgrade.
FPM_CONF="$(basename "$(ls /etc/apache2/conf-available/php*-fpm.conf | head -n1)" .conf)"
[ -n "$FPM_CONF" ] || die "no php*-fpm.conf found; is php-fpm installed?"

a2enmod proxy_fcgi setenvif rewrite headers >/dev/null
a2enconf "$FPM_CONF" >/dev/null

# The vhost is the same file the container uses, with only ServerName changed —
# which is exactly the claim docker/everything4cats.conf makes about itself. Copying
# and substituting keeps that claim true instead of aspirational.
# Owned by www-data from the moment it exists. Found by the container test on
# 2026-08-01: created as root, the later `wp core download` runs as www-data and
# dies with "'/var/www/everything4cats/' is not writable by current user". The chown
# further down came after the download, which is too late to help.
install -d -o www-data -g www-data "$WP_DIR"
sed "s/ServerName localhost/ServerName $SITE_DOMAIN\n    ServerAlias www.$SITE_DOMAIN/" \
	"$REPO_DIR/docker/everything4cats.conf" > /etc/apache2/sites-available/everything4cats.conf

a2ensite everything4cats >/dev/null

# Refuse xmlrpc.php. Server scope, not vhost scope, so it also covers the SSL
# vhost certbot generates later and that this script does not manage. See the
# header of docker/e4c-xmlrpc.conf for what it closes and why Apache rather than
# a WordPress filter. a2enconf is idempotent, so a re-run is a no-op.
install -m 0644 "$REPO_DIR/docker/e4c-xmlrpc.conf" \
	/etc/apache2/conf-available/e4c-xmlrpc.conf
a2enconf e4c-xmlrpc >/dev/null
# 000-default answers on the same *:80 with no ServerName, so whichever loaded
# first wins and the Apache welcome page shows instead of the site.
a2dissite 000-default >/dev/null 2>&1 || true
apache2ctl configtest
svc reload apache2
svc start apache2

# --- wp-cli -----------------------------------------------------------------
#
# Official phar, not the Debian package, which lags badly. Same two lines as the
# Dockerfile.

if ! command -v wp >/dev/null; then
	log "Installing WP-CLI"
	curl -fsSL -o /usr/local/bin/wp \
		https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
	chmod +x /usr/local/bin/wp
	wp --allow-root --info >/dev/null
fi

# www-data's home is /var/www, which it does not own, so WP-CLI cannot create its
# cache and prints "Failed to create directory '/var/www/.wp-cli/cache/'" on
# every call. Creating it with the right owner silences that at the source rather
# than by redirecting warnings away.
install -d -o www-data -g www-data /var/www/.wp-cli/cache
wp_run() { sudo -u www-data -- wp --path="$WP_DIR" "$@"; }

# --- database ---------------------------------------------------------------

log "Database"

# Started explicitly rather than assumed. On any host with systemd both are
# started at install time, so this is a no-op there; in a container nothing
# starts them and every
# mysql call below would fail with a socket error that reads like a permissions
# problem. Being explicit costs nothing and removes a whole class of confusing
# first-run failure.
svc start mysql
svc start "$FPM_CONF"
sleep 2

# Container only. systemd-tmpfiles normally creates /run/mysqld as 0755, and
# without it mysqld's own startup leaves the directory 0700 mysql:mysql. The
# socket inside is world-writable, but www-data cannot traverse the directory to
# reach it, so WordPress reports "Error establishing a database connection"
# while the identical credentials work from a root shell. Guarded to no-systemd
# hosts so it never touches permissions systemd owns on a real server.
if ! has_systemd && [ -d /run/mysqld ]; then
	chmod 0755 /run/mysqld
fi

if mysql -N -B -e "SHOW DATABASES LIKE '$DB_NAME';" | grep -q "$DB_NAME"; then
	echo "database $DB_NAME already exists, leaving it alone"
	DB_PASS=""
else
	# Silent read. Never a script default, never an argument, so it stays out of
	# the process list and the shell history.
	read -rsp "New password for MySQL user '$DB_USER': " DB_PASS; echo
	[ -n "$DB_PASS" ] || die "database password cannot be empty."

	# utf8mb4 so emoji and non-Latin scripts survive. utf8 in MySQL is three
	# bytes and silently truncates at the first four-byte character.
	mysql -e "CREATE DATABASE \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
	mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
	mysql -e "GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';"
	mysql -e "FLUSH PRIVILEGES;"
fi

# --- wordpress core ---------------------------------------------------------

log "WordPress core"

if [ ! -f "$WP_DIR/wp-includes/version.php" ]; then
	sudo -u www-data -- wp --path="$WP_DIR" core download
fi
chown -R www-data:www-data "$WP_DIR"

if [ ! -f "$WP_DIR/wp-config.php" ]; then
	[ -n "$DB_PASS" ] || die "wp-config.php is missing but the database already existed, so its password is not known here. Write wp-config.php by hand, or drop the database and re-run."

	# Salts come from the WordPress.org API, which wp config create calls itself.
	wp_run config create \
		--dbname="$DB_NAME" --dbuser="$DB_USER" --dbpass="$DB_PASS" \
		--dbcharset=utf8mb4 --dbcollate=utf8mb4_unicode_ci --skip-check

	# Pinned by constant rather than left in the database, so the site cannot be
	# half-migrated by an option row someone forgot. The container does the same
	# against http://localhost:8080.
	wp_run config set WP_HOME    "$SITE_SCHEME://$SITE_DOMAIN" --type=constant
	wp_run config set WP_SITEURL "$SITE_SCHEME://$SITE_DOMAIN" --type=constant

	# File edit from wp-admin is a code-execution path for any compromised admin
	# account, and this theme is deployed from Git rather than edited in place.
	wp_run config set DISALLOW_FILE_EDIT true --raw --type=constant
fi
unset DB_PASS

# Trust the proxy's protocol header, when there is a proxy.
#
# Written into wp-config.php with sed rather than `wp config set`, because this
# is a conditional, not a constant, and it has to run before WordPress decides
# whether the current request is secure.
#
# Only the header set by our own vhost is trusted. X-Forwarded-Proto is
# client-supplied on a directly-exposed host, so this is guarded behind an
# explicit opt-in rather than being on by default: turning it on where nothing
# strips the incoming header would let a visitor assert their own connection
# was secure when it was not.
if [ -n "$BEHIND_TLS_PROXY" ] && ! grep -q 'E4C_PROXY_TLS' "$WP_DIR/wp-config.php"; then
	log "Trusting the reverse proxy's X-Forwarded-Proto"

	# Shell tools only. The container image this runs in has no python3, and an
	# earlier draft of this block used it, which would have failed on the server
	# at the one moment there is no working site to debug from.
	[ "$(head -n 1 "$WP_DIR/wp-config.php")" = "<?php" ] \
		|| die "wp-config.php does not open with a bare <?php on line 1; refusing to edit it blindly."

	E4C_TMP="$(mktemp)"
	{
		printf '%s\n' '<?php'
		cat <<'PHPEOF'

/* E4C_PROXY_TLS: TLS terminates at the reverse proxy in front of this host,
   so the request arrives here as plain HTTP. Without this, WordPress compares
   http against an https WP_HOME and redirects to https forever.
   The vhost overwrites this header on every request, so a client cannot set it. */
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO'] ) {
	$_SERVER['HTTPS'] = 'on';
}
PHPEOF
		tail -n +2 "$WP_DIR/wp-config.php"
	} > "$E4C_TMP"

	cat "$E4C_TMP" > "$WP_DIR/wp-config.php"
	rm -f "$E4C_TMP"
	chown www-data:www-data "$WP_DIR/wp-config.php"
	sudo -u www-data -- php -l "$WP_DIR/wp-config.php" >/dev/null \
		|| die "wp-config.php failed to parse after adding the proxy check."
fi

if ! wp_run core is-installed 2>/dev/null; then
	read -rsp "Password for the new WordPress admin '$ADMIN_USER': " ADMIN_PASS; echo
	[ -n "$ADMIN_PASS" ] || die "admin password cannot be empty."

	wp_run core install \
		--url="$SITE_SCHEME://$SITE_DOMAIN" \
		--title="$SITE_TITLE" \
		--admin_user="$ADMIN_USER" \
		--admin_password="$ADMIN_PASS" \
		--admin_email="$ADMIN_EMAIL" \
		--skip-email
	unset ADMIN_PASS

	# Discourage search engines, on a FRESH INSTALL ONLY.
	#
	# WordPress installs with blog_public=1, so without this a brand new site is
	# indexable from its first minute, carrying nothing but the Hello World post
	# and the Sample Page. Those are the pages Google crawls fastest, and they
	# become the site's first impression. Found on the real host 2026-08-11 and
	# corrected by hand there, which is why it is codified here.
	#
	# INSIDE the core-install guard on purpose, never unconditional. This script
	# is re-run by design (the theme phase re-runs it), and an unconditional
	# `option update blog_public 0` would silently de-index a launched site on
	# the next deploy. The failure would be invisible for weeks, because nothing
	# about the site looks different when it is noindexed.
	#
	# Flipping it back to 1 is a launch step, listed in the Remaining block.
	wp_run option update blog_public 0 >/dev/null

	# The byline WordPress publishes, distinct from the login used to sign in.
	#
	# `wp core install` sets display_name and user_nicename to the admin login.
	# plugins/e4c-compliance publishes display_name into the Article JSON-LD on
	# every post, and user_nicename becomes the author archive URL, so the
	# default leaks the login in machine-readable form on every page. Found
	# 2026-08-11.
	#
	# Optional rather than required, and skipped loudly when unset, matching how
	# THEME_DIR behaves. A byline is a content decision and this script has no
	# basis to invent one.
	#
	# Inside the core-install guard for the same reason blog_public is: outside
	# it, every redeploy would overwrite a display name changed in wp-admin. The
	# consequence is that setting this variable and re-running does nothing to an
	# existing install. Changing the byline on a running site is a direct
	# `wp user update`, documented in README.md under Provisioning a server.
	if [ -n "$ADMIN_DISPLAY_NAME" ]; then
		wp_run user update "$ADMIN_USER" \
			--display_name="$ADMIN_DISPLAY_NAME" \
			--user_nicename="$(printf '%s' "$ADMIN_DISPLAY_NAME" | tr '[:upper:] ' '[:lower:]-')" \
			>/dev/null
	else
		skipped "byline: ADMIN_DISPLAY_NAME is not set, so display_name is the login '$ADMIN_USER' and will be published in Article schema on every post"
	fi
fi

# Pretty permalinks. Requires AllowOverride All, which the vhost already sets;
# without it every URL except the home page 404s.
#
# Flat, not '/%category%/%postname%/'. A category in the path means a post's URL
# changes whenever it is recategorised, and a post in two categories gets one of
# them picked for it. The topical grouping that structure buys is carried by
# breadcrumbs and internal links instead, neither of which breaks a live URL.
wp_run rewrite structure '/%postname%/' >/dev/null
wp_run rewrite flush --hard >/dev/null

# `wp rewrite flush --hard` writes the BEGIN/END WordPress markers but leaves
# them empty when it cannot detect Apache, which it cannot from the CLI. The
# result is a site where every URL except the home page 404s, with an .htaccess
# that looks correct at a glance because the markers are there. Observed locally
# 2026-08-01. Written explicitly rather than trusted.
if ! grep -q 'RewriteEngine On' "$WP_DIR/.htaccess" 2>/dev/null; then
	cat > "$WP_DIR/.htaccess" <<'HTACCESS'

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
HTACCESS
	chown www-data:www-data "$WP_DIR/.htaccess"
fi

# --- theme ------------------------------------------------------------------
#
# Deployed by symlink from the checkout, matching the container, so a git pull is
# the whole deploy and there is no copy step to forget.

log "Theme"
THEMES_DIR="$WP_DIR/wp-content/themes"

# THEME_DIR is the directory name of the theme inside this checkout. It is not
# hardcoded because the base theme is supplied separately and is not in the
# repository yet; until it is, provisioning leaves WordPress on its bundled
# default rather than failing or activating something that does not exist.
THEME_DIR="${THEME_DIR:-}"

if [ -z "$THEME_DIR" ]; then
	skipped "theme: THEME_DIR is not set, leaving the default theme active"
elif [ ! -d "$REPO_DIR/$THEME_DIR" ]; then
	die "THEME_DIR=$THEME_DIR is set but $REPO_DIR/$THEME_DIR does not exist."
else
	# Symlinked from the checkout, so a git pull is the whole deploy and there is
	# no copy step to forget.
	if [ ! -e "$THEMES_DIR/$THEME_DIR" ]; then
		ln -s "$REPO_DIR/$THEME_DIR" "$THEMES_DIR/$THEME_DIR"
	fi
	wp_run theme activate "$THEME_DIR"
fi

# Plugins that travel with the repository rather than coming from
# wordpress.org, linked the same way the theme is so a git pull is the whole
# deploy.
#
# Every directory under plugins/ is deployed. This was hardcoded to
# e4c-compliance until 2026-08-12, when plugins/e4c-content arrived carrying the
# review and roundup post types and was silently not deployed. The theme depends
# on those post types, so the symptom was not "a plugin is missing" but
# "/reviews/ 404s and every review template is unreachable", which reads as a
# broken theme. Iterating the directory means the next repo plugin cannot
# reintroduce that.
for plugin_src in "$REPO_DIR"/plugins/*/; do
	[ -d "$plugin_src" ] || continue
	plugin_slug="$(basename "$plugin_src")"

	if [ ! -e "$WP_DIR/wp-content/plugins/$plugin_slug" ]; then
		ln -s "${plugin_src%/}" "$WP_DIR/wp-content/plugins/$plugin_slug"
	fi

	# No error suppression. Activating an already-active plugin warns and exits
	# 0, so the only thing `|| true` used to hide was a real activation failure,
	# such as a fatal in the plugin itself. That is precisely the failure worth
	# stopping for.
	wp_run plugin activate "$plugin_slug" >/dev/null
done

# --- plugins ----------------------------------------------------------------
#
# Read from scripts/plugins.txt so this list exists in exactly one place.

log "Plugins"
# Read on fd 3, not stdin. `wp` inherits stdin and will happily consume the rest
# of the plugin list, so a plain `while read ... done < file` installs the first
# plugin and silently skips the others.
while read -r line <&3; do
	line="${line%%#*}"
	line="$(echo "$line" | xargs || true)"
	[ -n "$line" ] || continue

	slug="${line%%:*}"
	if [ "$line" = "${slug}:delete" ]; then
		# Shipped inside the WordPress tarball rather than installed from
		# wordpress.org, so `wp core download` brings them back on every fresh
		# install and they have to be removed rather than simply not installed.
		# Guarded by is-installed so a re-run after they are already gone is a
		# no-op rather than an error, since every deploy after the first is a
		# re-run.
		if wp_run plugin is-installed "$slug" 2>/dev/null; then
			wp_run plugin delete "$slug" >/dev/null
		fi
	elif [ "$line" = "${slug}:inactive" ]; then
		wp_run plugin is-installed "$slug" 2>/dev/null || wp_run plugin install "$slug"
	else
		wp_run plugin is-installed "$slug" 2>/dev/null || wp_run plugin install "$slug"
		wp_run plugin activate "$slug" >/dev/null
	fi
done 3< "$REPO_DIR/scripts/plugins.txt"

# --- hardening --------------------------------------------------------------

log "Swap"
# Ubuntu cloud images generally ship without swap, Lightsail included. This
# creates 2 GiB at low swappiness (vm.swappiness=10), so it is reached under
# pressure rather than used routinely. MySQL, PHP workers, and image processing
# sharing 2 GiB of RAM is exactly where a WordPress host OOMs, and the OOM
# killer usually takes MySQL, which looks like data corruption rather than
# memory pressure.
if ! has_systemd; then
	skipped "swap: containers cannot swapon; this runs on the real host only"
elif [ "$(swapon --show --noheadings | wc -l)" -eq 0 ] && [ ! -f /swapfile ]; then
	fallocate -l 2G /swapfile
	chmod 600 /swapfile
	mkswap /swapfile >/dev/null
	swapon /swapfile
	grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
	# Low, not zero. Swapping is a last resort here, not routine paging.
	sysctl -q -w vm.swappiness=10
	grep -q '^vm.swappiness' /etc/sysctl.conf || echo 'vm.swappiness=10' >> /etc/sysctl.conf
else
	echo "swap already present, leaving it alone"
fi

log "Firewall and fail2ban"
# ufw is the host-level layer. Lightsail always puts a second, separate firewall
# in front of it, configured in the console per instance, and the two can
# disagree silently. A port opened in the console but closed here simply does not
# work, and neither place says why. When a port appears dead, check both.
#
# OpenSSH is allowed before enabling, which is the difference between a firewall
# and a lockout. Recovering from a lockout means the provider's console recovery
# path, so the ordering here is load-bearing on every provider.
if has_systemd; then
	ufw allow OpenSSH >/dev/null
	ufw allow 'Apache Full' >/dev/null
	ufw --force enable >/dev/null
	systemctl enable --now fail2ban >/dev/null
else
	skipped "firewall and fail2ban: no init system; this runs on the real host only"
fi

# --- TLS --------------------------------------------------------------------
#
# Deliberately last, and deliberately not run. Certbot fails and burns a rate
# limit if DNS does not already resolve to this host, and pointing DNS is an
# outward-facing action that belongs to the human, not to a script.

log "Done"
cat <<EOF

Provisioned: $SITE_SCHEME://$SITE_DOMAIN  (not yet TLS)

Remaining, in order, and yours to run. Everything above this line targets
Ubuntu. Everything below touches the hosting provider, currently AWS Lightsail.

  1. Attach a static IP to this instance, in the Lightsail console.
     The address an instance gets by default is released when the instance is
     stopped and started, so without this the address changes under you. That
     breaks DNS and TLS renewal later, not now, which is the hard kind of
     breakage to trace back.

  2. Point DNS: an A record for $SITE_DOMAIN and one for www, both at that
     static IP, in the registrar's DNS panel. DNS is deliberately not delegated
     to Route 53. Confirm it resolves before step 4, or certbot burns a rate
     limit against a name that points nowhere:

       dig +short $SITE_DOMAIN
       dig +short www.$SITE_DOMAIN

     Check from a resolver outside the registrar too. A panel showing a record
     saved is not the same as the internet seeing it.

  3. Open 80 and 443 in the Lightsail firewall for this instance.
     That firewall is separate from the ufw rules this script just set, and it
     always applies. A port open in ufw but closed there is closed, and nothing
     in either place explains why.

  4. Issue the certificate:

       certbot --apache -d $SITE_DOMAIN -d www.$SITE_DOMAIN

     Then prove renewal works, rather than finding out in ninety days:

       certbot renew --dry-run

     If a CAA record is added later to pin issuance to one authority, re-run
     that dry run. Let's Encrypt reads CAA from the authoritative nameservers
     with no cache, so the dry run is the only definitive test, and a malformed
     CAA record fails silently until the day renewal is due.

  5. Check SSH before changing it. Verified 2026-08-11: the Ubuntu cloud image
     already ships key-only, so this is usually a confirmation rather than an
     edit. Read the effective config, not the file:

       sshd -T | grep -iE '^(passwordauthentication|kbdinteractiveauthentication|pubkeyauthentication|permitrootlogin|permitemptypasswords) '

     Use sshd -T because Ubuntu drops overrides into sshd_config.d/*.conf, so
     sshd_config can say one thing while the daemon does another. Check
     kbdinteractiveauthentication as well as passwordauthentication: with the
     first left on alongside UsePAM, PAM can still complete a password-equivalent
     exchange while the second reads as disabled.

     Key-only auth is the boundary. Restricting the source address in the
     Lightsail firewall is defence in depth on top of it, and it is only
     practical from a static address. Behind a VPN with a rotating exit address
     it causes routine self-lockout, so it was deliberately not applied here.

     Do not close 22 outright. The browser SSH client in the console is a rescue
     path, not a working admin channel, so leaving 22 reachable from somewhere
     is the difference between locked down and locked out. That rescue claim is
     inherited and has not been tested against a restrictive firewall rule, so
     test it before relying on it.

  6. Configure FluentSMTP. Outbound port 25 is blocked by default, so this needs
     a relay over 587/465 or an HTTP API rather than direct delivery. Until it
     is done, password resets and comment notifications fail silently. The site
     looks fine and the mail is gone.

  7. Set up backups at both layers, because they fail differently.
     Enable automatic snapshots for the instance in the Lightsail console.
     Nothing is backed up unless you turn it on. Then configure UpdraftPlus to
     off-site storage as the application-level backup, take one, and confirm it
     restores. A backup nobody has restored is not a backup.

  8. Activate the page cache only once the site is live:

       sudo -u www-data wp --path=$WP_DIR plugin activate wp-super-cache

  9. At launch, and last, make the site indexable:

       sudo -u www-data wp --path=$WP_DIR option get blog_public   # expect 0
       sudo -u www-data wp --path=$WP_DIR option update blog_public 1

     This script sets it to 0 on a fresh install, so the site is not crawled
     while it carries only Hello World and Sample Page. Delete those fixtures
     before flipping it, because they are the pages a search engine reaches
     first.

     The same switch gates the sitemaps. Submit the sitemap to Search Console on
     the day you flip this and not before, since submitting one that is not
     being served teaches Search Console the sitemap is broken.

EOF
